# Site settings
title: AppClinic 2015
email: AppClinic@compsoc.lk
url: https://example.github.io
description: "Computer Science Society of University of Colombo in collaboration with Google Developer Group Sri Lanka pompously adduces you the GDG Android App Clinic 2015. GDG Android App Clinic is an annual event which lay before for the undergraduates all over the country the opportunity of painting the innovativeness on the canvas of Android Games encouraged by the reviews, experiences and supportiveness of the industry experts on android platforms.  Our effort is to open the nation’s doors for a newer and an exciting tomorrow of ICT."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#ffffff'
  links: '#219ab3'
  nav_color: '#7ebf41'

# Footer settings
footer: GDG App Clinic 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url: https://www.facebook.com/events/478177039030895/


# Build settings
markdown: kramdown
permalink: pretty


